IT4995/IT4995/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('user/', include('customer.urls')),
    path('adminsite/', include('adminsite.urls')),
]

IT4995/hotel/urls.py
from django.urls import  path
from django.views.generic import TemplateView

from . import views
from .views import *
app_name = 'hotel'

urlpatterns = [
    path('', HomePage.as_view(), name = 'Homepage'),
    path('about/', TemplateView.as_view(template_name='hotel/about.html')),
    path('contact/', TemplateView.as_view(template_name='hotel/contacts.html')),
    path('support/', TemplateView.as_view(template_name='hotel/support.html')),
    path('category/',Category,name = 'Category'),
    path('category/<str:name>/', Category_Detail ,name = 'Category_detail'),
    path('category/<str:name>/room/', Category_Room ,  name = 'Category_Room'),
    path('profile/', profile, name = 'profile'),
    path('room/', my_room, name = 'my_room'),
    path('available_room/',availble_list, name='avail_room'),
]

IT4995/hotel/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# model category room
from django.db.models import UniqueConstraint
from django.urls import reverse


class service(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/service')
    link_url = models.CharField(max_length=40)
    description = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Categories(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=1500, default='')
    description_home = models.CharField(max_length=500, default='')
    image = models.ImageField(upload_to='static/images/categories', default='')
    price_randian = models.FloatField(default=0)
    service_list = models.ManyToManyField(service)
    def __str__(self):
        return self.name
    # category detail
    def get_absolute_url(self):
        return reverse('hotel:Category_detail', args=[self.name])

    # list room of category
    def get_absolute_url1(self):
        return reverse('hotel:Category_Room', args=[self.name])
#     list comment of category
    def get_absolute_url2(self):
        return reverse('hotel:Category_detail', args=[self.name])



# model room
class Rooms(models.Model):
    name = models.CharField(max_length=200, unique=True)
    category = models.ForeignKey('Categories', on_delete=models.CASCADE)
    status = models.IntegerField(default=0)
    description = models.CharField(max_length=200, default='')
    image = models.ImageField(upload_to='static/images/rooms')

    def __str__(self):
        return self.name

class Voucher(models.Model):
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    # %
    discount = models.FloatField(default=0)
    qty = models.IntegerField(default=0)
    description = models.CharField(max_length=100, null=True)
    create_date = models.DateField(default= date.today())
    end_date = models.DateField(null=True)

    def __str__(self):
        return self.name
STATUS_BOOKING = [
        ('PENDING', 'Pending'),
        ('CONFIRM', 'Confirm'),
        ('OCCUPIED','Occupied'),
        ('RETURNED','Returned'),
        ('CANCEL','Cancel')
    ]
# model book a room

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    number_adults = models.IntegerField(default=0)
    number_children = models.IntegerField(default=0)
    arival_date = models.DateField()
    departure_date = models.DateField()
    UniqueConstraint(fields=['user', 'room'], name='unique_user_booking')
    status = models.CharField(max_length=10, choices= STATUS_BOOKING, default='PENDING')
    voucher = models.ForeignKey(Voucher, on_delete=models.SET_NULL, null= True)
    def __str__(self):
        return self.user.first_name

    def Fee(self):
        time = (self.departure_date - self.arival_date)
        fee = int(time.days)*self.room.category.price_randian
        if self.voucher is None:
            return int(fee)
        else:
            return int(fee*(1-self.voucher.discount/100))
    def Discount(self):

        if self.voucher is None:
            return 0
        else:
            time = (self.departure_date - self.arival_date)
            fee = (int(time.days) * self.room.category.price_randian)
            return int(fee*(self.voucher.discount/100))
    def get_display_fee(self):
        return self.Fee()*100
    def Name(self):
        return self.user.first_name + ' ' + self.user.last_name
    def Email(self):
        return self.user.username

IT4995/hotel/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic.base import View
from datetime import datetime
from customer.models import Comments
from customer.views import *
from .models import *

class HomePage(View):

    def get(self, request, *args,**kwargs):
        # lấy toàn bộ danh sách các loại phòng
        categories_lst = Categories.objects.all()
        comment_lst = Comments.objects.all()
        context = {
            'categories_lst' : categories_lst,
            'comment_lst': comment_lst,
        }
        return render(request, 'hotel/index.html', context=context)

def Category(request):
    categories_lst = Categories.objects.all()
    comment_lst = Comments.objects.all()
    context = {
        'categories_lst': categories_lst,
        'comment_lst': comment_lst,
    }
    return render(request, 'hotel/categories.html',context=context)

def Category_Detail(request, name = None):
    category = get_object_or_404(Categories, name = name)
    cmt_lst = Comments.objects.filter(category=category)
    context = {
        'category':category,
        'comments':cmt_lst,
    }
    return render(request, 'hotel/room_category.html',  context= context)

def Category_Room(request, name = None):
    category = get_object_or_404(Categories, name = name)
    cate_lst = Categories.objects.all()
    room_lst = Rooms.objects.filter(category=category)
    comments = Comments.objects.filter(category=category)
    ser = service.objects.all()
    context = {
        'cate_lst': cate_lst,
        'category': category,
        'room_lst': room_lst,
        'comments':comments,
        'ser':ser,

    }
    return render(request,'hotel/room_list.html', context= context)

def profile(request):
    return render(request, 'hotel/index.html', )

def my_room(request):
    return render(request, 'hotel/index.html', )


# list availble room
def availble_list(request):
    if request.method == 'POST':
        check_in_date = request.POST['check_in']
        check_out_date = request.POST['check_out']
        adults = request.POST['adults']
        children = request.POST['children']
        print(check_in_date)
        print(check_out_date)
        try:
            i = format_date(check_in_date)
            o = format_date(check_out_date)
        except:
            return redirect('hotel:Homepage')
        room_lst = Rooms.objects.all()
        avail_room = []
        for room in room_lst:
            avail_room.append(room)
        for room in room_lst:
            booking1 = Booking.objects.filter(room=room, status='PENDING')
            booking2 = Booking.objects.filter(room=room, status='CONFIRM')
            booking3 = Booking.objects.filter(room=room, status='OCCUPIED')
            if len(booking1) != 0:
                for b in booking1:
                    if b.departure_date >= datetime.strptime(i, '%Y-%m-%d').date() and b.arival_date <= datetime.strptime(o,'%Y-%m-%d').date():
                        avail_room.remove(b.room)
            elif len(booking2)!= 0:
                for b in booking2:
                    if b.departure_date >= datetime.strptime(i, '%Y-%m-%d').date() and b.arival_date <= datetime.strptime(
                            o, '%Y-%m-%d').date():
                        avail_room.remove(b.room)
            elif len(booking3)!= 0:
                for b in booking2:
                    if b.departure_date >= datetime.strptime(i, '%Y-%m-%d').date() and b.arival_date <= datetime.strptime(
                            o, '%Y-%m-%d').date():
                        avail_room.remove(b.room)
        print(avail_room)
        avail_room = list(set(avail_room))
        context = {
            'categories_lst': Categories.objects.all(),
            'room_lst' : avail_room,
            'check_in':check_in_date,
            "check_out":check_out_date,
            'adults' : adults,
            'children': children,
        }

        return render(request, 'hotel/avail_room.html',context=context)

IT4995/templates/hotel/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About Us {% endblock %}
{% block sub %} Our Wonderfull Rooms {% endblock %}

{% block body %}
{% block sub_body %}
    <div class="container margin_60">
      <h2 class="main_title"><em></em>Welcome to Albert <span>Hotel and Bed&amp;Breakfast</span></h2>
        <p class="lead styled">
            Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie. Sed ad debet scaevola, ne mel lorem legendos. Unum etiam cum te, an elit assueverit vix, falli aliquam complectitur ex ius.
        </p>

    	<div class="row about">
                <div class="col-md-5 col-sm-6 col-md-offset-1">
                   <h3>A beatiful contest</h3>
                        <p>
                            Esse dicit accusam duo an. Modus simul ei nec. Sea et explicari pertinacia, <strong>cu vitae bonorum</strong> vocibus nec, corpora signiferumque no vim. Ad principes scriptorem duo, te omnium gubergren eam, et eam ancillae appareat dissentiet. Quando tantas animal vis ut, mandamus voluptatum duo ne, ne odio vidit commodo has.
                        </p>
                </div>
                <div class="col-md-4 col-sm-6 col-md-offset-1">
                <img src="{% static 'img/about_1.jpg' %}" alt="" class="img-responsive styled">
                </div>
      </div><!-- End row -->
 		<div class="divider hidden-xs"></div>
       <div class="row about" >
            <div class="col-md-5 col-sm-6 col-md-offset-1 col-md-push-5">
                 <h3>Charming rooms</h3>
                        <p>
                            Esse dicit accusam duo an. Modus simul ei nec. Sea et explicari pertinacia, <strong>cu vitae bonorum</strong> vocibus nec, corpora signiferumque no vim. Ad principes scriptorem duo, te omnium gubergren eam, et eam ancillae appareat dissentiet. Quando tantas animal vis ut, mandamus voluptatum duo ne, ne odio vidit commodo has.
                        </p>
            </div>
            <div class="col-md-4 col-sm-6 col-md-offset-1 col-md-pull-6">
               <img src="{% static 'img/about_2.jpg' %}" alt="" class="img-responsive styled">
            </div>
        </div><!-- End row -->
      <div class="divider hidden-xs"></div>
        <div class="row about">
                <div class="col-md-5 col-sm-6 col-md-offset-1">
                   <h3>Enjoy and relax</h3>
                        <p>
                            Esse dicit accusam duo an. Modus simul ei nec. Sea et explicari pertinacia, <strong>cu vitae bonorum</strong> vocibus nec.
                        </p>
                        <ul class="list_ok">
                        	<li>Spa and Sauna</li>
                            <li>Body treatments</li>
                             <li>Swimming pool</li>
                        </ul>
                </div>
                <div class="col-md-4 col-sm-6 col-md-offset-1">
                <img src="{% static 'img/about_3.jpg' %}" alt="" class="img-responsive styled">
                </div>
      </div><!-- End row -->
    </div><!-- End container -->

{% endblock %}

 <div class="container_styled_1">
    	<div class="container margin_60">
        <h3 class="main_title">General facilities<span>Ad principes scriptorem duo, te omnium gubergren eam.</span></h3>
        	<div class="row">
            	<div class="col-md-4 col-sm-4">
                	<div class="box_feat">
                    	<i class="icon_set_1_icon-8"></i>
                        <h4>Patio garden</h4>
                        <p>Ut postea legendos vim, usu an reque novum inimicus, cum aperiri molestiae splendide ea. Ad nam modus iudico rationibus.</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4">
                <div class="box_feat">
                    	<i class="icon_set_1_icon-27"></i>
                        <h4>Parking</h4>
                        <p>Ut postea legendos vim, usu an reque novum inimicus, cum aperiri molestiae splendide ea. Ad nam modus iudico rationibus.</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4">
                <div class="box_feat">
                    	<i class="icon_set_1_icon-14"></i>
                        <h4>Room service</h4>
                        <p>Ut postea legendos vim, usu an reque novum inimicus, cum aperiri molestiae splendide ea. Ad nam modus iudico rationibus.</p>
                    </div>
                </div>
            </div><!-- End row -->
            <div class="row">
            	<div class="col-md-4 col-sm-4">
                	<div class="box_feat">
                    	<i class="icon_set_1_icon-22"></i>
                        <h4>Pet allowed</h4>
                        <p>Ut postea legendos vim, usu an reque novum inimicus, cum aperiri molestiae splendide ea. Ad nam modus iudico rationibus.</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4">
                <div class="box_feat">
                    	<i class="icon_set_2_icon-103"></i>
                        <h4>Loundry service</h4>
                        <p>Ut postea legendos vim, usu an reque novum inimicus, cum aperiri molestiae splendide ea. Ad nam modus iudico rationibus.</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4">
                <div class="box_feat">
                    	<i class="icon_set_1_icon-13"></i>
                        <h4>Disable</h4>
                        <p>Ut postea legendos vim, usu an reque novum inimicus, cum aperiri molestiae splendide ea. Ad nam modus iudico rationibus.</p>
                    </div>
                </div>
            </div><!-- End row -->
        </div><!-- End container -->
    </div><!-- End container_styled_1 -->

    <div class="grid">
		<ul class="magnific-gallery" style="margin-bottom:-5px;">
						<li>
							<figure>
								<img src="{% static 'img/gallery/pic_1.jpg' %}" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="img/gallery/large/pic_1.jpg" title="Photo title">
										<i class="icon_set_1_icon-32"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="{% static 'img/gallery/pic_2.jpg' %}" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="img/gallery/large/pic_2.jpg" title="Photo title">
										<i class="icon_set_1_icon-32"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="{% static 'img/gallery/pic_3.jpg' %}" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="img/gallery/large/pic_3.jpg" title="Photo title">
										<i class="icon_set_1_icon-32"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="{% static 'img/gallery/pic_4.jpg' %}" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="img/gallery/large/pic_4.jpg" title="Photo title">
										<i class="icon_set_1_icon-32"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
					</ul>
		</div>
{% endblock %}
    

IT4995/templates/hotel/categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Category Room List {% endblock %}
{% block sub %} Our Wonderfull Rooms {% endblock %}

{% block body %}
<div class="container margin_60">
    <div class="row">
        <div class="col-lg-9 col-md-8">
            {% for category in categories_lst %}
            <div class="row">
                <div class="room_desc clearfix" onclick="location.href='{{ category.get_absolute_url2 }}';">
                                <div class="col-md-7">
                                    <figure><img src="{{ category.image.url }} " alt="" class="img-responsive"></figure>
                                </div>
                                <div class="col-md-5 room_list_desc">
                                    <h3>{{category.name}}</h3>
                                    <p>{{ category.description_home }}</p>
                                    <ul style="display: flex; width:100%;">
                                        {% for s in category.service_list.all %}
                                        <li >
                                            <div class="tooltip_styled tooltip-effect-4">
                                                <span class="tooltip-item"><i class="{{s.description}}"></i></span>
                                	        <div class="tooltip-content">{{ s.name }}</div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    <div class="price">from <strong>${{category.price_randian}}</strong> /night<small>Breakafst
                                        included</small></div>
                                </div>
                            </div>
                        </div><!-- End row room -->
                        {% endfor %}
                    </div>
                    <div class="col-lg-3 col-md-4 sidebar">

                        <div class="theiaStickySidebar">
                            <div class="box_style_3" id="general_facilities">
                                <h3>General facilities</h3>
                                <ul>
                                    <li><i class="icon_set_1_icon-86"></i>Free Wifi</li>
                                    <li><i class="icon_set_2_icon-103"></i>Loundry service</li>
                                    <li><i class="icon_set_2_icon-110"></i>Swimming pool</li>
                                    <li><i class="icon_set_1_icon-58"></i>Restaurant</li>
                                    <li><i class="icon_set_1_icon-27"></i>Parking</li>
                                </ul>
                            </div>
                            <div class="box_style_2">
                                <i class="icon_set_1_icon-90"></i>
                                <h4>Need help? Call us</h4>
                                <a href="tel://yourNumber" class="phone">Your Number</a>
                                <small>Monday to Friday 9.00am - 7.30pm</small>
                            </div>

                        </div>
                    </div>

                </div><!-- End row -->
            </div><!-- End container -->


            {% endblock %}


            {% block scripts %}
            <!-- SPECIFIC SCRIPTS -->
            <script src="{% static 'js/theia-sticky-sidebar.js' %}"></script>
            <script>
    jQuery('.sidebar').theiaStickySidebar({
      additionalMarginTop: 80
    });


            </script>

            {% endblock %}

IT4995/templates/hotel/index.html
{% extends 'base.html' %}
{% load static %}


{% block subheader_home %}
    <div id="subheader_home" style="height: 230px">
    <div id="sub_content">
                <div id="book_container">
                    <form method="post" action="{%  url 'hotel:avail_room' %}" id="check_avail_home" autocomplete="off">
                        {% csrf_token %}
                        <input type="hidden" name="data" id="data">
                        <div id="group_1">
                            <div id="container_1">
                                <label>Arrival date</label>
                                    <input class="date-pick form-control" type="text" id="check_in" name="check_in"
                                           placeholder="Check in" data-date-format="M d D" readonly>
                                    <span class="input-icon"><i class="icon-calendar-7"></i></span>
                            </div>
                            <div id="container_2">
                                <label>Departure date</label>
                                    <input class="date-pick form-control" type="text" id="check_out" name="check_out"
                                           placeholder="Check out" data-date-format="M d D" readonly>
                                    <span class="input-icon"><i class="icon-calendar-7"></i></span>
                            </div>
                        </div><!-- End group_1 -->
                        <div id="group_2">
                            <div id="container_3">
                                <label>Adults</label>
                                <div class="qty-buttons">
                                    <input type="button" value="-" class="qtyminus" name="adults">
                                    <input type="text" name="adults" id="adults" value="" class="qty form-control" placeholder="0">
                                    <input type="button" value="+" class="qtyplus" name="adults">
                                </div>
                            </div>
                            <div id="container_4">
                                <label>Children</label>
                                <div class="qty-buttons">
                                    <input type="button" value="-" class="qtyminus" name="children">
                                    <input type="text" name="children" id="children" value="" class="qty form-control" placeholder="0">
                                    <input type="button" value="+" class="qtyplus" name="children">
                                </div>
                            </div>
                        </div><!-- End group_2 -->

                        <div id="container_7">
                            <input type="submit" value="Check availability" class="btn_1" id="submit-booking">
                        </div>
                    </form>
                </div><!-- End book_container -->
            </div><!-- End sub_content -->
    </div>
{% endblock %}

{% block body %}
{% block sub_body %}
<div class="container margin_60_35">
    <h1 class="main_title"><em></em>Welcome to Recom <span>Hotel and Bed&amp;Breakfast</span></h1>
    <p class="lead styled">
        Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes molestie. Sed ad debet
        scaevola, ne mel lorem legendos. Unum etiam cum te, an elit assueverit vix, falli aliquam complectitur ex ius.
    </p>
    <div class="row">
        <div class="col-sm-6">
            <div class="mosaic_container">
                <img src="{% static 'img/mosaic_1.jpg' %}" alt="" class="img-responsive add_bottom_30"><span
                    class="caption_2">Nice Outdoor</span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="col-xs-12">
                <div class="mosaic_container">
                    <img src="{% static 'img/mosaic_2.jpg' %}" alt="" class="img-responsive add_bottom_30"><span
                        class="caption_2">Large Bedroom</span>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="mosaic_container">
                    <img src="{% static 'img/mosaic_3.jpg' %}" alt="" class="img-responsive add_bottom_30"><span
                        class="caption_2">Modern Bathroom</span>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="mosaic_container">
                    <img src="{% static 'img/mosaic_4.jpg' %}" alt="" class="img-responsive add_bottom_30"><span
                        class="caption_2">Wellness</span>
                </div>
            </div>
        </div>
    </div><!-- End row -->
</div><!-- End container -->
{% endblock %}



{% for category in categories_lst %}
<div class="container_styled_1">
    <div class="container margin_60">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <figure class="room_pic"><img src="{{ category.image.url }}" alt=""
                                                          class="img-responsive"><span class="wow zoomIn"
                                                                                           data-wow-delay="0.2s" style="width:35%;"><sup>$</sup>{{category.price_randian}}<small>Per night</small></span>
                </figure>
            </div>
            <div class="col-md-4 col-md-offset-1">
                <div class="room_desc_home">
                    <h3>{{category.name}}</h3>
                    <p>
                        {{category.description_home}}
                    </p>
                    <ul style="display: flex; width:100%;">
                                        {% for s in category.service_list.all %}
                                        <li >
                                            <div class="tooltip_styled tooltip-effect-4">
                                                <span class="tooltip-item"><i class="{{s.description}}"></i></span>
                                	        <div class="tooltip-content">{{ s.name }}</div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                    <a href="{{ category.get_absolute_url }}" class="btn_1_outline">Read more</a>
                </div><!-- End room_desc_home -->
            </div>
        </div><!-- End row -->
    </div><!-- End container -->
</div><!-- End container_styled_1 -->

{% endfor %}
<section class="promo_full">
    <div class="promo_full_wp">
        <div>
            <h3>What Clients say<span>Id tale utinam ius, an mei omnium recusabo iracundia.</span></h3>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="carousel_testimonials">
                            {% for c in comments %}
                            <div>
                                <div class="box_overlay">
                                    <div class="pic">
                                        <figure><img src="{% static 'img/testimonial_1.jpg' %}" alt=""
                                                     class="img-circle"></figure>
                                        <h4>{{c.user.first_name}} {{c.user.last_name}}<small>{{c.create_date}}</small></h4>
                                    </div>
                                    <div class="comment">
                                        {{ c.comment }}
                                         </div>
                                </div><!-- End box_overlay -->
                            </div>
                            {% endfor %}
                        </div><!-- End carousel_testimonials -->
                    </div><!-- End col-md-8 -->
                </div><!-- End row -->
            </div><!-- End container -->
        </div><!-- End promo_full_wp -->
    </div><!-- End promo_full -->
</section><!-- End section -->

{%endblock%}

<!-- SPECIFIC SCRIPTS -->
{% block scripts %}
<script>
  $('.carousel_in').owlCarousel({
    center: true,
    items:1,
    loop:true,
	 autoplay:true,
	 navText: [ '', '' ],
	addClassActive: true,
    margin:-1,
    responsive:{
        600:{
            items:1
        },
		 1000:{
            items:2,
			nav:true,
        }
    }
});

</script>

</script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/bootsrap_datepicker_func.js' %}"></script>

</script>

{% endblock %}

IT4995/templates/hotel/room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
category room
</body>
</html>