IT4995/IT4995/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('user/', include('customer.urls')),
    path('adminsite/', include('adminsite.urls')),
]

IT4995/adminsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *
app_name = 'adminsite'

urlpatterns = [
    path('', admin_site, name = 'admin site'),
    path('category', admin_site_category, name='admin_site_category'),
    path('room', admin_site_room, name='admin_site_room'),
    path('booking', admin_site_booking, name='admin_site_booking'),
    path('add_category', admin_site_add_category, name='admin_site_add_category'),
    path('add_room', admin_site_add_room, name='admin_site_add_room'),
    path('add_service/',admin_site_add_service, name= 'admin_site_add_service')

]

IT4995/hotel/urls.py
from django.urls import  path
from django.views.generic import TemplateView

from . import views
from .views import *
app_name = 'hotel'

urlpatterns = [
    path('', HomePage.as_view(), name = 'Homepage'),
    path('about/', TemplateView.as_view(template_name='hotel/about.html')),
    path('contact/', TemplateView.as_view(template_name='hotel/contacts.html')),
    path('support/', TemplateView.as_view(template_name='hotel/support.html')),
    path('category/',Category,name = 'Category'),
    path('category/<str:name>/', Category_Detail ,name = 'Category_detail'),
    path('category/<str:name>/room/', Category_Room ,  name = 'Category_Room'),
    path('profile/', profile, name = 'profile'),
    path('room/', my_room, name = 'my_room'),
    path('available_room/',availble_list, name='avail_room'),
]

IT4995/adminsite/models.py
from django.db import models

# Create your models here.

IT4995/adminsite/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from datetime import date, datetime
from hotel.models import *
from customer.models import *

@login_required(login_url='/admin/')
def admin_site(request):
    if not request.user.is_staff:
        return redirect('/admin')
    booking = Booking.objects.all()
    room = Rooms.objects.all()
    comment = Comments.objects.all()
    context = {
        'booking': len(booking),
        'room':len(room),
        'comment': len(comment),
        'room_lst': room,
        'booking_lst': booking,
    }
    return render(request, 'adminsite/main.html/', context= context)


@login_required(login_url='/login_user/')
def admin_site_category(request):
    category_lst = Categories.objects.all()
    context = {
        'categories': category_lst
    }
    return render(request, 'adminsite/category.html', context=context)
@login_required(login_url='/login_user/')
def admin_site_room(request):
    room_lst = Rooms.objects.all()
    context = {
        'rooms': room_lst
    }
    return render(request, 'adminsite/room.html', context=context)
@login_required(login_url='/login_user/')
def admin_site_booking(request):
    # booking_lst = Booking.objects.all()
    # context = {
    #     'books': booking_lst
    # }
    # return render(request, 'adminsite/booking.html', context=context)
    return reverse('hotel/booking')


@login_required(login_url='/login_user/')
def admin_site_add_category(request):
    if request.method == 'GET':
        service_lst = service.objects.all()
        context = {
            'ser_lst': service_lst
        }
        return render(request, 'adminsite/add_category.html', context=context)
    else:
        name_category = request.POST['name']
        price = request.POST['price']
        des = (request.POST['description'])
        ser_lst = request.POST.getlist('service')
        cate = Categories.objects.create(name=name_category, description=des, price_randian=price)
        for ser in ser_lst:
            s = get_object_or_404(service, name=ser)
            cate.service_list.add(s)
        cate.save()
        return redirect('admin_site_category')
@login_required(login_url='/login_user/')
def admin_site_add_room(request):
    if request.method == 'GET':
        categories = Categories.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'adminsite/add_room.html', context=context)
    else:
        name = request.POST['name']
        price = request.POST['price']
        des = (request.POST['description'])
        cate_lst = request.POST.getlist('category')
        cate = get_object_or_404(Categories, name=cate_lst[0])
        room = Rooms.objects.create(name=name, price=price, description=des, status=0, category=cate)
        room.save()
        return redirect('admin_site_room')


# delete booking
def admin_booking_room_delete(request,id):
    if not request.user.is_staff:
        return redirect('/admin')
    try:
        room = Booking.objects.get(pk=id)
        room.room.status = 0
        room.room.save()
        room.delete()
    except:
        pass
    return redirect('admin_booking')

def admin_site_add_service(request):
    return redirect('hotel:Homepage')

IT4995/templates/adminsite/add_category.html
{% extends 'adminsite/base.html' %}
{% load static %}

<body>
{% block body %}
{% block sub_body %}
<div class="row">
    <div class="col-md-12">
              <div class="card ">
                <div class="card-header card-header-rose card-header-text">
                  <div class="card-text">
                    <h4 class="card-title">Form Elements</h4>
                  </div>
                </div>
                <div class="card-body ">
                  <form method="POST" action="{% url 'adminsite:admin_site_add_category' %}" class="form-horizontal">
                      {% csrf_token %}
                    <div class="row">
                      <label class="col-sm-2 col-form-label">Category Name</label>
                      <div class="col-sm-10">
                        <div class="form-group">
                          <input type="text" name="name" class="form-control">
                          <span class="bmd-help">A block of help text that breaks onto a new line.</span>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <label class="col-sm-2 col-form-label">Price</label>
                      <div class="col-sm-10">
                        <div class="form-group">
                          <input type="text" name="price" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <label class="col-sm-2 col-form-label">Description</label>
                      <div class="col-sm-10">
                        <div class="form-group">
                          <input type="text" name="description" class="form-control" placeholder="description for category">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <label class="col-sm-2 col-form-label label-checkbox">Services list</label>
                      <div class="col-sm-10 checkbox-radios">
                        {% for ser in ser_lst %}
                        <div class="form-check">
                          <label class="form-check-label">
                            <input class="form-check-input" name="service" id="{{ ser.name}}" type="checkbox" value="{{ser.name }}"> {{ser.name }}
                            <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                          </label>
                        </div>
                          {% endfor %}
                      </div>
                    </div>
                    <div class="row">
                        <div class="card-footer ">
                        <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                        </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
</div>

{% endblock%}
{% endblock %}
</body>

IT4995/templates/adminsite/add_room.html
{% extends 'adminsite/base.html' %}
{% load static %}

<body>
{% block body %}
{% block sub_body %}
<div class="row">
    <div class="col-md-12">
              <div class="card ">
                <div class="card-header card-header-rose card-header-text">
                  <div class="card-text">
                    <h4 class="card-title">Form Elements</h4>
                  </div>
                </div>
                <div class="card-body ">
                  <form method="POST" action="{% url 'adminsite:admin_site_add_room' %}" class="form-horizontal">
                      {% csrf_token %}
                    <div class="row">
                      <label class="col-sm-2 col-form-label">Room Number</label>
                      <div class="col-sm-10">
                        <div class="form-group">
                          <input type="text" name="name" class="form-control">
                          <span class="bmd-help">A block of help text that breaks onto a new line.</span>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <label class="col-sm-2 col-form-label">Price</label>
                      <div class="col-sm-10">
                        <div class="form-group">
                          <input type="text" name="price" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <label class="col-sm-2 col-form-label">Description</label>
                      <div class="col-sm-10">
                        <div class="form-group">
                          <input type="text" name="description" class="form-control" placeholder="description for category">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <label class="col-sm-2 col-form-label label-checkbox">Services list</label>
                      <div class="col-sm-10 checkbox-radios">
                        {% for category in categories %}
                        <div class="form-check">
                          <label class="form-check-label">
                            <input class="form-check-input" name="category" id="{{ category.name}}" type="checkbox" value="{{category.name }}"> {{category.name }}
                            <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                          </label>
                        </div>
                          {% endfor %}
                      </div>
                    </div>
                    <div class="row">
                        <div class="card-footer ">
                        <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                        </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
</div>

{% endblock%}
{% endblock %}
</body>

IT4995/templates/adminsite/booking.html
{% extends 'adminsite/base.html' %}
{% load static %}

<body>
{% block body %}
{% block sub_body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                  <div class="card-header card-header-icon card-header-rose">
                    <div class="card-icon">
                      <i class="material-icons">assignment</i>
                    </div>
                    <h4 class="card-title ">Booking Table</h4>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table">
                        <thead class=" text-primary">
                          <th>
                            ID
                          </th>
                          <th>
                            Username
                          </th>
                          <th>
                            Room
                          </th>
                          <th>
                            Check In
                          </th>
                            <th>
                            Check Out
                          </th>
                        <th>
                            Adults
                          </th>
                        <th>
                            Children
                          </th>
                        </thead>
                        <tbody style="color: #ed5434;">
                        {% for book in books %}
                          <tr>
                            <td>
                              {{ book.id }}
                            </td>
                            <td>
                                {{ book.user }}
                            </td>
                            <td>
                              {{ book.room}}
                            </td>
                              <td>
                                {{ book.arival_date }}
                            </td>
                            <td>
                                {{ book.departure_date }}
                            </td>
                            <td>
                                {{ book.number_adults }}
                            </td>
                            <td>
                                {{ book.number_children }}
                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
        </div>
{% endblock%}
{% endblock %}
</body>

IT4995/templates/adminsite/category.html
{% extends 'adminsite/base.html' %}
{% load static %}

<body>
{% block body %}
{% block sub_body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                  <div class="card-header card-header-icon card-header-rose">
                    <div class="card-icon">
                      <i class="material-icons">assignment</i>
                    </div>
                    <h4 class="card-title ">Category Table</h4>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table">
                        <thead class=" text-primary">
                          <th>
                            ID
                          </th>
                          <th>
                            Name
                          </th>
                          <th>
                            Price
                          </th>
                          <th>Service</th>
                        </thead>
                        <tbody>
                        {% for cate in categories %}
                          <tr style="color: #ed5434;">
                            <td>
                              {{ cate.id }}
                            </td>
                            <td>
                                {{ cate.name }}
                            </td>
                            <td>
                              {{ cate.price_randian}} $/night
                            </td>
                            <td>
                              <ul>
                                {% for s in cate.service_list.all %}
                                <li><small>{{s.name}}</small></li>
                              {% endfor %}
                              </ul>

                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
        </div>
{% endblock%}
{% endblock %}
</body>

IT4995/templates/adminsite/room.html
{% extends 'adminsite/base.html' %}
{% load static %}

<body>
{% block body %}
{% block sub_body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
                <div class="card">
                  <div class="card-header card-header-icon card-header-rose">
                    <div class="card-icon">
                      <i class="material-icons">assignment</i>
                    </div>
                    <h4 class="card-title ">Room Table</h4>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table">
                        <thead class=" text-primary">
                          <th>
                            ID
                          </th>
                          <th>
                            Name
                          </th>
                          <th>
                            Category
                          </th>
                          <th>
                            Price
                          </th>
                            <th>
                            Status
                          </th>
                        </thead>
                        <tbody style="color: #ed5434;">
                        {% for room in rooms %}
                          <tr>
                            <td>
                              {{ room.id }}
                            </td>
                            <td>
                                {{ room.name }}
                            </td>
                            <td>
                              {{ room.category}}
                            </td>
                              <td>
                                {{ room.price }}
                            </td>
                              <td>
                                {{ room.status }}
                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
        </div>
{% endblock%}
{% endblock %}
</body>