IT4995/IT4995/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('user/', include('customer.urls')),
    path('adminsite/', include('adminsite.urls')),
]

IT4995/customer/urls.py
from django.urls import  path
from . import views
from .views import *
app_name = 'customer'

urlpatterns = [
    path('booking/',Cus_Booking.as_view(), name = 'booking_room'),
    path('comment/', Comment,name = 'create_comment'),
    path('login_user/', login_user, name ='Login'),
    path('signup',sign_up, name = 'sign_up'),
    path('profile/',profile,name='profile'),
    path('change_password/', change_password, name='change_password'),
    path('logout/', Logout, name='logout'),
    path('cancel/', cancel_booking, name="cancel"),
]

IT4995/hotel/urls.py
from django.urls import  path
from django.views.generic import TemplateView

from . import views
from .views import *
app_name = 'hotel'

urlpatterns = [
    path('', HomePage.as_view(), name = 'Homepage'),
    path('about/', TemplateView.as_view(template_name='hotel/about.html')),
    path('contact/', TemplateView.as_view(template_name='hotel/contacts.html')),
    path('support/', TemplateView.as_view(template_name='hotel/support.html')),
    path('category/',Category,name = 'Category'),
    path('category/<str:name>/', Category_Detail ,name = 'Category_detail'),
    path('category/<str:name>/room/', Category_Room ,  name = 'Category_Room'),
    path('profile/', profile, name = 'profile'),
    path('room/', my_room, name = 'my_room'),
    path('available_room/',availble_list, name='avail_room'),
]

IT4995/customer/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
# model signup user
from hotel.models import Categories
from IT4995 import settings  # <- Change to match your main app name


class Signup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=20, default='')
    def __str__(self):
        return self.user.username


class Comments(models.Model):
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    evaluation = models.CharField(max_length=200, default='')
    comment = models.CharField( max_length=200 , null=False, default="good")
    create_date = models.DateField( default= date.today())

    def __str__(self):
        return self.user.username + ' comment: ' + self.category.name

IT4995/customer/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.hashers import make_password, check_password
# Create your views here.
from django.views.generic.base import View
from hotel.models import *
from .models import *
# Create your views here.
from django.utils.decorators import method_decorator
from django.http import HttpResponse

class Cus_Booking(View):
    def get(self, request, *args, **kwargs):
        my_booking = Booking.objects.filter(user=request.user)
        return render(request, 'customer/my_room_test.html', {'booking_list': my_booking})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        data = request.POST['data']
        check_in_date = request.POST['check_in']
        check_out_date = request.POST['check_out']
        adults = (request.POST['adults'])
        children = (request.POST['children'])
        voucher_code = request.POST['voucher_code']
        try:
            adults = 0 if (adults == '') else int(adults)
            children = 0 if (children == '') else int(children)
            i = format_date(check_in_date)
            o = format_date(check_out_date)
        except:
            return  redirect('hotel:Category_detail', name = data)
        if data is not None and adults != 0 and (adults + children) <= 10:
            room_lst = Rooms.objects.filter(category__in=Categories.objects.filter(name = data))
            avail_room = []
            for room in room_lst:
                avail_room.append(room)
            for room in room_lst:
                booking1 = Booking.objects.filter(room=room, status='PENDING')
                booking2 = Booking.objects.filter(room=room, status='CONFIRM')
                booking3 = Booking.objects.filter(room=room, status='OCCUPIED')
                if len(booking1) != 0:
                    for b in booking1:
                        if b.departure_date >= datetime.strptime(i,
                                                                '%Y-%m-%d').date() or b.arival_date <= datetime.strptime(
                                o, '%Y-%m-%d').date():
                            avail_room.remove(b.room)
                elif len(booking2) != 0:
                    for b in booking2:
                        if b.departure_date >= datetime.strptime(i,
                                                                '%Y-%m-%d').date() or b.arival_date <= datetime.strptime(
                                o, '%Y-%m-%d').date():
                            avail_room.remove(b.room)
                elif len(booking3) != 0:
                    for b in booking2:
                        if b.departure_date >= datetime.strptime(i,
                                                                '%Y-%m-%d').date() or b.arival_date <= datetime.strptime(
                                o, '%Y-%m-%d').date():
                            avail_room.remove(b.room)
            avail_room = list(set(avail_room))
            if len(avail_room) != 0:
                voucher = Voucher.objects.filter(code=voucher_code).first()
                print(voucher)
                if voucher is not None:
                    if voucher.qty > 0 and voucher.create_date < datetime.strptime(i,
                                                                                   '%Y-%m-%d').date() and voucher.end_date > datetime.strptime(
                            i, '%Y-%m-%d').date():
                        a = Booking.objects.create(room=avail_room[0], user=request.user, number_adults=adults,
                                                   number_children=children,
                                                   arival_date=i, departure_date=o, voucher=voucher)
                        voucher.qty -= 1
                        voucher.save()
                        a.save()
                        booking_id = a.id
                    else:
                        a = Booking.objects.create(room=avail_room[0], user=request.user, number_adults=adults,
                                                   number_children=children,
                                                   arival_date=i, departure_date=o)
                        a.save()
                        booking_id = a.id
                else:
                    a = Booking.objects.create(room=avail_room[0], user=request.user, number_adults=adults,
                                               number_children=children,
                                               arival_date=i, departure_date=o)
                    a.save()
                    booking_id = a.id
            else:
                return HttpResponse('<h1>No Room</h1>')
        else:
            return redirect('hotel:Category_detail', name = data)
        my_booking = Booking.objects.filter(user=request.user)
        print(booking_id)
        return render(request, 'customer/my_room_test.html', {'booking_list': my_booking})


def cancel_booking(request):
    if request.method == 'POST':
        book_id = request.POST['cancel_booking']
        b= Booking.objects.get(id = book_id)
        try:
            b.status = "CANCEL"
            b.save()
        except:
            pass
    return redirect('customer:booking_room')

def login_user(request):
    if request.user.is_authenticated:
        return redirect('hotel:Homepage')
    error = ''
    if request.method == 'POST':
        email = request.POST['email']
        pwd = request.POST['pwd']
        user = authenticate(username=email, password=pwd)
        try:
            if user:
                login(request, user)
                error = 'no'
            else:
                error = 'yes'
        except:
            error = 'yes'
    try:
        next_page = request.GET['next']
    except:
        next_page = ''
    return render(request, 'customer/login_user.html', {'error': error, 'next_page': next_page})

@login_required
def Comment(request):
    if request.method == 'POST':
        room_type_review = request.POST['room_type_review']
        position_review = request.POST['position_review']
        comfort_review = request.POST['comfort_review']
        price_review = request.POST['price_review']
        quality_review = request.POST['quality_review']
        review_text = request.POST['review_text']
        evals = "Position: " + position_review + ' Comfort: ' + comfort_review + ' Price: ' + price_review + ' Quality: ' + quality_review
        category = Categories.objects.filter(name=room_type_review).first()
        if category is None or category == '':
            return redirect('hotel:Category')
        if room_type_review != '':
            tmp = Comments.objects.create(category=category, user=request.user, evaluation=evals, comment=review_text)
            tmp.save()
            return redirect('hotel:Category_detail', name=category)
        else:
            return redirect('hotel:Category_detail', name=category)
    return redirect('hotel:Category_detail')

def format_date(datetime):
    datetime = datetime.split()
    day = datetime[1] if datetime[1] >= '10' else '0' + datetime[1]
    month = {'Jan': '01', 'Feb': '02', 'Mar': '03', 'Apr': '04', 'May': '05', 'Jun': '06', 'Jul': '07', 'Aug': '08',
             'Sep': '09', 'Oct': '10', 'Now': '11', 'Dec': '12'}
    year = date.today().year
    return '-'.join([str(year), month[datetime[0]], day])

#
def sign_up(request):
    if request.user.is_authenticated:
        return redirect('index')
    error = ""
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        contact = request.POST['contact']
        email = request.POST['email']
        password = request.POST['pwd']
        try:
            user = User.objects.create_user(username=email, password=password, first_name=first_name,
                                            last_name=last_name)
            Signup.objects.create(user=user, contact=contact)
            error = 'no'
        except:
            error = 'yes'
    d = {'error': error}
    return render(request, 'customer/sign_up.html', d)


@login_required
def profile(request):
    if not request.user.is_authenticated:
        return redirect('customer:Login')
    data = Signup.objects.get(user=request.user.username)
    print(data)
    return render(request, 'customer/profile.html', {'data': data})

# to change password user
@login_required
def change_password(request):
    if not request.user.is_authenticated:
        return redirect('login_user')
    error = ""
    if request.method == 'POST':
        o_p = request.POST['o-pwd']
        n_p = request.POST['n-pwd']
        c_p = request.POST['c-pwd']
        u = User.objects.get(username__exact=request.user.username)
        if not check_password(o_p, u.password):
            error = "yes"
        elif c_p == n_p:
            u.password = make_password(n_p)
            u.save()
            error = "no"
        else:
            error = "yes"
    d = {"error": error}
    return render(request, 'customer/changepassword.html', d)


def Logout(request):
    logout(request)
    return redirect('hotel:Homepage')

IT4995/templates/customer/changepassword.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Change Password {% endblock %}

{% block sub %} Change Password {% endblock %}
<br/>
<br/>
{% block body %}
{% ifequal error "no" %}
<script>
    alert('Password Changeed...')
    window.location=('{% url "customer:logout" %}')
</script>

{% endifequal %}
{% ifequal error "yes" %}
<script>
    alert("Something Went Wrong!")
</script>
{% endifequal %}

<div class="container mt-5 " style="background-color: whitesmoke;">
    <div class="row">
        <div class="col-sm-6">
            <br/>
            <img src="{% static 'img/slides/slide_1.jpg' %}" alt="" width="90%" height="300px">
        </div>
        <div class="col-sm-6">
            <h2 class="text-center">CHANGE PASSWORD</h2>
            <hr>
            <form action="" method="POST">
                    {% csrf_token %}
                <label for="Old Password">Old Password</label>
                <input type="password" class="form-control" id="Old Password" placeholder="Enter Your Old Password" name="o-pwd">
                <label for="New Password">New Password</label>
                <input type="password" class="form-control" id="New Password" placeholder="Enter New Password" name="n-pwd">
                <label for="New Password Again">New Password Again</label>
                <input type="password" class="form-control" id="New Password Again" placeholder="Enter New Password Again" name="c-pwd">
                <input type="submit" class="btn btn-danger mt-2" value="SUBMIT">
            </form>
        </div>
    </div>
</div>

<br/>
<br/>
{% endblock %}

IT4995/templates/customer/login_user.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
{% ifequal error "no" %}
<script>
    alert('Logged In Successfully');
     window.location=(" {{next_page}} ");
</script>
{% endifequal %}

{% ifequal error "yes" %}
<script>
    alert('Invalid Login Credentials, Try Again');

</script>
    {% endifequal %}
<div class="container mt-5 " style="background-color: whitesmoke;">
    <div class="row">
        <div class="col-sm-6">
            <h2 class="text-center">NEW CUSTOMER</h2>
            <hr>
            <p>By Creating an account with our website, u will be able to move through the notes upload
                and downloading process and more...</p>
            <center><a href="{% url 'customer:sign_up' %}" class="btn btn-danger text-white mt-5 ">CREATE AN ACCOUNT</a></center>
        </div>
        <div class="col-sm-6">
            <h2 class="text-center">USER LOGIN</h2>
            <hr>
            <form action="" method="post">
                    {% csrf_token %}
                <label for="Email">Email Address</label>
                <input type="email" class="form-control" id="Email" placeholder="Enter EmailID" name="email" required>
                <label for="Password">Password</label>
                <input type="password" class="form-control" id="Password" placeholder="Enter Password" required name="pwd">
                <input type="submit" class="btn btn-danger mt-2" value="LOGIN">
            </form>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
</body>
</html>

IT4995/templates/customer/my_room_test.html
{% extends 'base.html' %}
{% load static %}
{% block title %} My Room List {% endblock %}
{% block sub %} Room List {% endblock %}
{% block body %}
<h1 class="main_title_in">My Room List</h1>
<div class="container add_bottom_60">
    <div class="row">
            <div class="row" style="padding-top: 15px;padding-bottom: 15px;text-align: center">
                <div class="col-md-1">Room</div>
                <div class="col-md-2">Category</div>
                <div class="col-md-1">Fee</div>
                <div class="col-md-2">Checkin</div>
                <div class="col-md-2">Checkout</div>
                <div class="col-md-2">Status</div>
                <div class="col-md-2">Action</div>
                <br>
            </div>
            {% if booking_list %}
                {% for book in booking_list %}
                    <div class="row" style="padding-top: 15px;padding-bottom: 15px;text-align: center; border-top: 1px solid #00a5bb; font-style: inherit">
                        <div class="col-md-1"><strong>{{book.room.name}}</strong></div>
                        <div class="col-md-2"><strong>{{book.room.category.name}}</strong></div>
                        <div class="col-md-1"><strong>{{ book.Fee }} $</strong></div>
                        <div class="col-md-2"><strong>{{book.arival_date}}</strong></div>
                        <div class="col-md-2"><strong>{{book.departure_date}}</strong></div>
                        <div class="col-md-2" style="color: red"><strong>{{ book.status }}</strong></div>
                        <div class="col-md-2" style="text-align: center;">
                            {% ifequal book.status "PENDING" %}
                                <form action="{% url 'customer:cancel' %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" style="margin-left:1%;" name="cancel_booking" value="{{ book.id}}" onclick="alert(' Are You Sure ?')" class="btn btn-danger mr-4"><span >Cancel </span></button>
                                </form>

                            {% endifequal %}
                            {% ifequal book.status "CONFIRM" %}

                                <form action="{% url 'customer:cancel' %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" style="margin-left:1%;" name="cancel_booking" value="{{ book.id}}" onclick="alert(' Are You Sure ?')" class="btn btn-danger mr-4"><span >Cancel </span></button>
                                </form>

                            {% endifequal %}
                            {% ifequal book.status "RETURNED" %}

                                <form action="{% url 'customer:cancel' %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" style="margin-left:1%;" name="cancel_booking" value="{{ book.id}}" onclick="alert(' Are You Sure ?')" class="btn btn-danger mr-4" disabled><span >Cancel </span></button>
                                </form>

                            {% endifequal %}
                            {% ifequal book.status "OCCUPIED" %}

                                <form action="{% url 'customer:cancel' %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" style="margin-left:1%;" name="cancel_booking" value="{{ book.id}}" onclick="alert(' Are You Sure ?')" class="btn btn-danger mr-4" disabled><span >Cancel </span></button>
                                </form>

                            {% endifequal %}
                            {% ifequal book.status "CANCEL" %}
                                <form action="{% url 'customer:cancel' %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" style="margin-left:1%;" name="cancel_booking" value="{{ book.id}}" onclick="alert(' Are You Sure ?')" class="btn btn-danger mr-4" disabled><span >Cancel </span></button>
                                </form>
                            {% endifequal %}
                        </div>
                        <br>
                    </div>
                    {% endfor %}
            {% else %}
                <h3 class="text-center">You have not made a reservation at the hotel</h3>
                <a href="{% url 'hotel:Category' %}" class="btn btn-danger" ><small>Booking Now</small></a>
            {% endif %}
    </div>
    <hr>
    <div class="row">
        <div class="col-md-8">
                <div class="col-md-3">
                    <h3>Policies</h3>
                </div>
                <div class="col-md-9">
                    <ul id="policies">
                        <li><i class="icon_set_1_icon-83"></i><h5>Check-in and check-out.</h5>
                            <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes
                                molestie. Sed ad debet scaevola, ne mel lorem legendos. Unum etiam cum te, an elit
                                assueverit vix, falli aliquam complectitur ex ius.</p>
                        </li>
                        <li><i class="icon_set_1_icon-54"></i><h5>Cancellation</h5>
                            <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes
                                molestie. Sed ad debet scaevola, ne mel lorem legendos. Unum etiam cum te, an elit
                                assueverit vix, falli aliquam complectitur ex ius.</p>
                        </li>
                        <li><i class="icon_set_1_icon-47"></i><h5>Smoking</h5>
                            <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes
                                molestie. Sed ad debet scaevola, ne mel lorem legendos. Unum etiam cum te, an elit
                                assueverit vix, falli aliquam complectitur ex ius.</p>
                        </li>
                        <li><i class="icon_set_1_icon-35"></i><h5>Payments</h5>
                            <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes
                                molestie. Sed ad debet scaevola, ne mel lorem legendos. Unum etiam cum te, an elit
                                assueverit vix, falli aliquam complectitur ex ius.</p>
                        </li>
                        <li><i class="icon_set_1_icon-13"></i><h5>Disable</h5>
                            <p>Usu habeo equidem sanctus no. Suas summo id sed, erat erant oporteat cu pri. In eum omnes
                                molestie. Sed ad debet scaevola, ne mel lorem legendos. Unum etiam cum te, an elit
                                assueverit vix, falli aliquam complectitur ex ius.</p>
                        </li>
                    </ul>
                </div>
        </div>
        <div class="col-md-4" id="sidebar">
            <div class="theiaStickySidebar">
                <div class="box_style_1">
                    <div id="message-booking"></div>
                    <h4 class="text-left" style="color: red;">To deposit and confirm the booking, please transfer money the following account number</h4>
                    <hr>
                    <label >Account Holder</label>
                    <input type="text" value="Account Holder" class="form-control" readonly style="outline-color: aqua;">
                    <label >Bank </label>
                    <input type="text" value="Bank" class="form-control" readonly style="outline-color: aqua;">
                    <label > Number Account </label>
                    <input type="text" value="Number Account" class="form-control" readonly style="outline-color: aqua;">
                    <hr>
                    <div href="#0" class=" btn_outline"> or Contact us</div>
                    <a href="tel://yourNumber" id="phone_2"><i class="icon_set_1_icon-91"></i>Your Number</a>

                </div><!-- End box_style -->
            </div><!-- End theiaStickySidebar -->
        </div><!-- End col -->
    </div>


</div><!-- End container -->


<div id="dtBox"></div><!-- End datepicker -->


{% endblock %}
{% block scripts %}
<!-- SPECIFIC SCRIPTS -->
<script>
    function addBooking(){
    listRoom = document.getElementsByName("room");
    data = document.getElementById('data');
    var str="";
    for(var i=0; i< listRoom.length; i++){
        if(listRoom[i].checked == true){
            str = str+ " " +listRoom[i].id;
        }
    }
    data.setAttribute("value",str);
}
</script>

<script>

  $('.carousel_in').owlCarousel({
    center: true,
    items:1,
    loop:true,
	 autoplay:true,
	 navText: [ '', '' ],
	addClassActive: true,
    margin:5,
    responsive:{
        600:{
            items:1
        },
		 1000:{
            items:2,
			nav:true,
        }
    }
});




</script>
<script src="{% static 'js/theia-sticky-sidebar.js' %}"></script>
<script>
    jQuery('#sidebar').theiaStickySidebar({
      additionalMarginTop: 80
    });


</script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/bootsrap_datepicker_func.js' %}"></script>
{% endblock %}

IT4995/templates/customer/profile.html
{% extends 'base.html' %}
{% block title %} Profile {% endblock %}

{% block sub %} PROFILE {% endblock %}
<br/>
<br/>
{% block body %}
<div class="container mt-5">
    <h2 class="text-center">PROFILE</h2>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <b>Full Name: </b>
        </div>
        <div class="col-md-6" style="text-transform: capitalize;">
            {{data.user.first_name}} {{data.user.last_name}}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <b>Email Id: </b>
        </div>
        <div class="col-md-6" style="text-transform: capitalize;">
            {{data.user.username}}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <b>Contact: </b>
        </div>
        <div class="col-md-6" style="text-transform: capitalize;">
            {{data.contact}}
        </div>
    </div>
    <hr>
    <a href="{% url 'customer:change_password' %}" class="btn btn-primary mt-5"> Change Password</a>

</div>
<br/>
<br/>
{% endblock %}

IT4995/templates/customer/sign_up.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>

<div class="container mt-5 " style="background-color: whitesmoke;">
    <div class="row">
        <div class="col-sm-6">
            <h2 class="text-center">EXISTING CUSTOMER</h2>
            <hr>
            <p>By Creating an account with our website, u will be able to move through the notes upload
                and downloading process and more...</p>
            <center><a href="{% url 'customer:Login' %}" class="btn btn-danger text-white mt-5 ">LOGIN NOW</a></center>
        </div>
        <div class="col-sm-6">
            <h2 class="text-center">REGISTER WITH US</h2>
            <hr>
            <p> If you have not an account with us , please sign up... </p>
            <form action="" method="post">
                {% csrf_token %}
                <label for="Firstname">First Name</label>
                <input type="text" id="Firstname" class="form-control" name="first_name" placeholder="Enter FirstName">
                <label for="Lastname">Last Name</label>
                <input type="text" id="Lastname" class="form-control" name="last_name" placeholder="Enter LastName">
                <label for="Contact">Contact</label>
                <input type="text" id="Contact" class="form-control" name="contact" placeholder="Enter Contact">
                <label for="Email">Email Address</label>
                <input type="email" class="form-control" id="Email" placeholder="Enter EmailID" name="email">
                <label for="Password">Password</label>
                <input type="password" class="form-control" id="Password" placeholder="Enter Password" name="pwd">
                <input type="submit" class="btn btn-danger mt-2" value="SUBMIT">
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>


{% ifequal error 'no' %}
<script>
    alert("Signup Successfull")
    window.location=("{% url 'customer:Login' %}")
</script>
{% endifequal %}
{% ifequal error 'yes' %}
<script>
    alert("Something Went Wrong, Try Again")
</script>
{% endifequal %}

</body>
</html>