IT4995/IT4995/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('user/', include('customer.urls')),
    path('adminsite/', include('adminsite.urls')),
]

IT4995/customer/urls.py
from django.urls import  path
from . import views
from .views import *
app_name = 'customer'

urlpatterns = [
    path('booking/',Cus_Booking.as_view(), name = 'booking_room'),
    path('comment/', Comment,name = 'create_comment'),
    path('login_user/', login_user, name ='Login'),
    path('signup',sign_up, name = 'sign_up'),
    path('profile/',profile,name='profile'),
    path('change_password/', change_password, name='change_password'),
    path('logout/', Logout, name='logout'),
    path('cancel/', cancel_booking, name="cancel"),
]

IT4995/hotel/urls.py
from django.urls import  path
from django.views.generic import TemplateView

from . import views
from .views import *
app_name = 'hotel'

urlpatterns = [
    path('', HomePage.as_view(), name = 'Homepage'),
    path('about/', TemplateView.as_view(template_name='hotel/about.html')),
    path('contact/', TemplateView.as_view(template_name='hotel/contacts.html')),
    path('support/', TemplateView.as_view(template_name='hotel/support.html')),
    path('category/',Category,name = 'Category'),
    path('category/<str:name>/', Category_Detail ,name = 'Category_detail'),
    path('category/<str:name>/room/', Category_Room ,  name = 'Category_Room'),
    path('profile/', profile, name = 'profile'),
    path('room/', my_room, name = 'my_room'),
    path('available_room/',availble_list, name='avail_room'),
]

IT4995/templates/base.html
<!DOCTYPE html>
<!--[if IE 9]>
<html class="ie ie9"> <![endif]-->
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="hotel, bed and breakfast, accommodations, travel, motel">
    <meta name="description" content="FC Recom - Hotel and Bed&amp;Breakfast">
    <meta name="author" content="Ansonika">
    <title>Sapa Hotel - {% block title %} Hotel and Bed&amp;Breakfast {%endblock%}</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="{% static 'img/apple-touch-icon-57x57-precomposed.png' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72"
          href="{% static 'img/apple-touch-icon-72x72-precomposed.png' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114"
          href="{% static 'img/apple-touch-icon-114x114-precomposed.png' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144"
          href="{% static 'img/apple-touch-icon-144x144-precomposed.png' %}">

    <!-- BASE CSS -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.css' %}">

    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.min.js"></script>
    <script src="{% static 'js/respond.min.js"></script>
    <![endif]-->

</head>
<body>

<!--[if lte IE 8]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a>.</p>
<![endif]-->

<div class="layer"></div>
<!-- Mobile menu overlay mask -->

<div id="preloader">
    <div data-loader="circle-side"></div>
</div><!-- End Preload -->

<!-- Header ================================================== -->

<header>
    <div class="container">
        <div class="row">
            <div class="col--md-3 col-sm-3 col-xs-3">
                <a href="/" id="logo">
                    <img src="{% static 'img/logo.png' %}" width="190" height="23" alt="" data-retina="true"
                         class="logo_normal">
                    <!--                <img src="{% static 'img/logo_sticky.png' %}" width="190" height="23" alt="" data-retina="true" class="logo_sticky">-->
                </a>
            </div>
            <nav class="col--md-9 col-sm-9 col-xs-9">
                <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
                <div class="main-menu">
                    <div id="header_menu">
                        <img src="{% static 'img/logo_m.png' %}" width="141" height="40" alt="" data-retina="true">
                    </div>
                    <a href="#" class="open_close" id="close_in"><i class="icon_set_1_icon-77"></i></a>
                    <ul>
                        <li class="submenu">
                            <a href="/" class="">Home</a>
                        </li>
                        

                         {% if request.user.is_authenticated %}
                                {% if not request.user.is_staff %}
                                    <li><a href="{% url 'hotel:Category' %}">Rooms</a></li>
                                    <li><a href="/contact">Contacts</a></li>
                                    <li><a href="/about">About Us</a></li>
                                    <li><a href="/support">Support</a></li>
                                    <li><a href="{% url 'customer:profile' %}">Profile</a></li>
                                    <li><a href="{% url 'customer:booking_room' %}">Booking</a></li>
                                    <li><a href="{% url 'customer:logout' %}">Logout</a></li>
                                    <li><div class="show-submenu"><i class="icon-user"></i> {{request.user.first_name}}  {{request.user.last_name}}</div></li>
                                {% else %}
                                    <li><a href="{% url 'admin:index' %}">Adminsite</a></li>
                                    <li><a href="/admin/hotel/rooms">Rooms</a></li>
                                    <li><a href="/admin/hotel/booking/">Booking</a></li>
                                    <li><a href="/admin/hotel/voucher/">Voucher</a></li>
                                    <li><a href="{% url 'customer:logout' %}">Logout</a></li>
                                    <li><div class="show-submenu"><i class="icon-user"></i> {{request.user.first_name}}  {{request.user.last_name}}</div></li>
                                {% endif %}
                        {% else %}
                        <li><a href="{% url 'hotel:Category' %}">Rooms</a></li>     
                        <li><a href="/about">About Us</a></li>
                        <li><a href="/support">Support</a></li>
                        <li><a href="/contact">Contacts</a></li>
                        <li><a href="{% url 'customer:Login' %}">Login</a></li>
                        <li><a href="{% url 'customer:sign_up' %}">Sign Up</a></li>
                        {% endif %}

                    </ul>
                </div><!-- End main-menu -->
            </nav>
        </div><!-- End row -->
    </div><!-- End container -->
</header>
<section class="parallax-window" id="short" data-parallax="scroll"
{#        data-image-src="{% static 'img/sub_header_home.jpg' %}" data-natural-width="1400" data-natural-height="550">}#}
         data-image-src="{% static 'img/banner/11.jpg' %}" data-natural-width="1400" data-natural-height="550">

    <div id="subheader">
        <h1>{% block sub %}Home{% endblock %}</h1>
    </div><!-- End subheader -->

</section><!-- End section -->


    {% block subheader_home %}

    {% endblock %}

<!-- End Header =============================================== -->
{% block body %}

{% block sub_body %} {% endblock %}

{% endblock %}

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <img src="{% static 'img/logo_footer.png' %}" width="141" height="40" alt="" id="logo_footer"
                     data-retina="true">
                <ul id="contact_details_footer">
                    <li>Your Address<br>Your Country</li>
                    <li><a href="tel://yourNumber">Your Number</a> / <a href="#0">
                        <script data-cfhash='f9e31' type="text/javascript">
                            /* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */

                        </script>
                    </a></li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-4">
                <h3>About</h3>
                <ul>
                    <li><a href="/about">About us</a></li>
                    <li><a href="{% url 'hotel:Category' %}">Category Room</a></li>
                    <li><a href="#">Activities</a></li>
                    <li><a href="/contact">Contact us</a></li>
                    <li><a href="#">Gallery</a></li>
                    <li><a href="/support">Support</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-4" id="newsletter">
                <h3>Newsletter</h3>
                <p>Join our newsletter to keep be informed about offers and news.</p>
                <div id="message-newsletter_2"></div>
                <form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
                    <div class="form-group">
                        <input name="email_newsletter_2" id="email_newsletter_2" type="email" value=""
                               placeholder="Your mail" class="form-control">
                    </div>
                    <input type="submit" value="Subscribe" class="btn_1 white" id="submit-newsletter_2">
                </form>
            </div>
        </div><!-- End row -->
        <div class="row">
            <div class="col-md-12">
                <div id="social_footer">
                    <ul>
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class="icon-google"></i></a></li>
                        <li><a href="#"><i class="icon-instagram"></i></a></li>
                        <li><a href="#"><i class="icon-pinterest"></i></a></li>
                        <li><a href="#"><i class="icon-vimeo"></i></a></li>
                        <li><a href="#"><i class="icon-youtube-play"></i></a></li>
                    </ul>
                    <p>Copyright © 2021 <a target="_blank" title="Free CSS Themes" href="http://freecssthemes.com/">Nguyen Duc Quyet</a>
                        | All Right Reserved</p>

                </div>
            </div>
        </div><!-- End row -->
    </div><!-- End container -->
</footer><!-- End footer -->

<div id="toTop"></div><!-- Back to top button -->

<!-- COMMON SCRIPTS -->
<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/common_scripts_min.js' %}"></script>
<script src="{% static 'assets/validate.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>

{% block scripts %} {% endblock %}
</body>
</html>